apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
spec:
  selector:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/name: vaultwarden
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
